default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://taskrpg:taskrpg123@localhost:5434/task_rpg_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://taskrpg:taskrpg123@localhost:5432/task_rpg_test") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
